spring.application.name=APIREV
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BDRevive
spring.datasource.username=postgres
spring.datasource.password=0101manuel
jwt.secret=052533f626bf983d73c878c9696b3fb3b4cd3325f6c49cf03624845a14f02f31